### PR TITLE
Restructure repository as an fpm package

### PR DESCRIPTION
**Pull request by LKedward**
Many thanks Mohammad @kookma for this great GNUPlot interface!

Would you be willing to accept the following changes so that the repository can be used as an [fpm](https://github.com/fortran-lang/fpm) package?

Changes:
- Move the interface module into `src` folder
- Move the example program into `example` folder
- Add `fpm.toml` manifest file
- Small workaround for bug with `gfortran-10`

### CODE REVIEW

**Review by kookma — APPROVED** [review]

**Review by kookma — APPROVED** [review]

**Comment by kookma** [comment]
Hi Laurence @LKedward 
That would be great! due lack of time I have not put enough time to maintain the package for a while! I have not used FPM, but it is  among the best, so I support your PR.

Have you thoroughly test it? If yes, I will merge!

**Comment by LKedward** [comment]
Thanks, yes I've tested it with fpm and haven't encountered any issues so far.

**Comment by kookma** [comment]
@LKedward I would appreciate if you kindly add the instruction for installing through FPM in Readme.md
I think you can add a section at the beginning as below


```
# ogpf
Object Based Interface to GnuPlot from Fortran (ogpf)

# Installation

## FPM
your explanation goes here ....

# Tutorial

## 2D Plots

````

**Comment by LKedward** [comment]
Ah yes of course, I had overlooked the README. I'll put together another PR.

**Pull request merged**
